#include <CosNotifyChannelAdmin.idl>
#include <notify_ext.idl>

module org {
  module jacorb {
    module notification {
    
      interface JacORBEventChannelFactory:
        ::CosNotifyChannelAdmin::EventChannelFactory,
        ::NotifyExt::ReconnectionRegistry
      {
		    void destroy();
      };
      
    };
  };
};
